// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikkS2DAXAyXAWuIBuhBOvQGB9Kbnb2ng',
    appId: '1:75356560459:web:0697efc0cbea55180681ce',
    messagingSenderId: '75356560459',
    projectId: 'alexandrie-694d2',
    authDomain: 'alexandrie-694d2.firebaseapp.com',
    storageBucket: 'alexandrie-694d2.appspot.com',
    measurementId: 'G-YRLWKQBSJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0UXBdZ672YeL1L7JbERusTtwjnKQQAc',
    appId: '1:75356560459:android:52847c627c7e89c00681ce',
    messagingSenderId: '75356560459',
    projectId: 'alexandrie-694d2',
    storageBucket: 'alexandrie-694d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9uCW_xQ4C-Zl4JR5I79SZSZczXqPYH-k',
    appId: '1:75356560459:ios:6ad09a66227f56400681ce',
    messagingSenderId: '75356560459',
    projectId: 'alexandrie-694d2',
    storageBucket: 'alexandrie-694d2.appspot.com',
    iosBundleId: 'com.example.alexandrie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9uCW_xQ4C-Zl4JR5I79SZSZczXqPYH-k',
    appId: '1:75356560459:ios:1537eceb4e100c2d0681ce',
    messagingSenderId: '75356560459',
    projectId: 'alexandrie-694d2',
    storageBucket: 'alexandrie-694d2.appspot.com',
    iosBundleId: 'com.example.alexandrie.RunnerTests',
  );
}
